### ISSUE TITLE
build problems

### ISSUE THREAD

**Issue by gijzelaerr** [radio-astro/casasynthesis#5]
any idea what is going wrong? Using casacore 2.0.3

```
/usr/bin/cmake -E cmake_progress_report /build/casasynthesis-0.1/obj-x86_64-linux-gnu/CMakeFiles
[ 11%] Building CXX object msvis/CMakeFiles/libmsvis.dir/MSVis/VisBufferImpl2.cc.o
cd /build/casasynthesis-0.1/obj-x86_64-linux-gnu/msvis && /usr/bin/x86_64-linux-gnu-g++   -DAIPS_AUTO_STL -DAIPS_STDLIB -DCASACORE_NEEDS_RETHROW -DCASA_USECASAPATH -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGEFILE_SOURCE -Dlibmsvis_EXPORTS -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -fPIC -I/build/casasynthesis-0.1 -I/usr/include/casacore    -o CMakeFiles/libmsvis.dir/MSVis/VisBufferImpl2.cc.o -c /build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2.cc
In file included from /build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2.cc:30:0:
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h: In instantiation of 'void casa::vi::VbCacheItemArray<T, IsComputed>::appendRows(casa::Int, casa::Bool) [with T = casa::Matrix<double>; bool IsComputed = false; casa::Int = int; casa::Bool = bool]':
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2.cc:2987:1:   required from here
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:417:13: error: 'class casa::Matrix<double>' has no member named 'reformOrResize'
             this->getItem().reformOrResize (shape, False);
             ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:447:17: error: 'class casa::Matrix<double>' has no member named 'adjustLastAxis'
                 this->getItem().adjustLastAxis (desiredShape, 20);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:454:17: error: 'class casa::Matrix<double>' has no member named 'reformOrResize'
                 this->getItem().reformOrResize (desiredShape);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h: In instantiation of 'void casa::vi::VbCacheItemArray<T, IsComputed>::appendRows(casa::Int, casa::Bool) [with T = casa::Vector<unsigned int>; bool IsComputed = false; casa::Int = int; casa::Bool = bool]':
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2.cc:2987:1:   required from here
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:417:13: error: 'class casa::Vector<unsigned int>' has no member named 'reformOrResize'
             this->getItem().reformOrResize (shape, False);
             ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:447:17: error: 'class casa::Vector<unsigned int>' has no member named 'adjustLastAxis'
                 this->getItem().adjustLastAxis (desiredShape, 20);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:454:17: error: 'class casa::Vector<unsigned int>' has no member named 'reformOrResize'
                 this->getItem().reformOrResize (desiredShape);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h: In instantiation of 'void casa::vi::VbCacheItemArray<T, IsComputed>::appendRows(casa::Int, casa::Bool) [with T = casa::Matrix<float>; bool IsComputed = false; casa::Int = int; casa::Bool = bool]':
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2.cc:2987:1:   required from here
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:417:13: error: 'class casa::Matrix<float>' has no member named 'reformOrResize'
             this->getItem().reformOrResize (shape, False);
             ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:447:17: error: 'class casa::Matrix<float>' has no member named 'adjustLastAxis'
                 this->getItem().adjustLastAxis (desiredShape, 20);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:454:17: error: 'class casa::Matrix<float>' has no member named 'reformOrResize'
                 this->getItem().reformOrResize (desiredShape);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h: In instantiation of 'void casa::vi::VbCacheItemArray<T, IsComputed>::appendRows(casa::Int, casa::Bool) [with T = casa::Cube<float>; bool IsComputed = false; casa::Int = int; casa::Bool = bool]':
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2.cc:2987:1:   required from here
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:417:13: error: 'class casa::Cube<float>' has no member named 'reformOrResize'
             this->getItem().reformOrResize (shape, False);
             ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:447:17: error: 'class casa::Cube<float>' has no member named 'adjustLastAxis'
                 this->getItem().adjustLastAxis (desiredShape, 20);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:454:17: error: 'class casa::Cube<float>' has no member named 'reformOrResize'
                 this->getItem().reformOrResize (desiredShape);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h: In instantiation of 'void casa::vi::VbCacheItemArray<T, IsComputed>::appendRows(casa::Int, casa::Bool) [with T = casa::Vector<bool>; bool IsComputed = false; casa::Int = int; casa::Bool = bool]':
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2.cc:2987:1:   required from here
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:417:13: error: 'class casa::Vector<bool>' has no member named 'reformOrResize'
             this->getItem().reformOrResize (shape, False);
             ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:447:17: error: 'class casa::Vector<bool>' has no member named 'adjustLastAxis'
                 this->getItem().adjustLastAxis (desiredShape, 20);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:454:17: error: 'class casa::Vector<bool>' has no member named 'reformOrResize'
                 this->getItem().reformOrResize (desiredShape);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h: In instantiation of 'void casa::vi::VbCacheItemArray<T, IsComputed>::appendRows(casa::Int, casa::Bool) [with T = casa::Cube<bool>; bool IsComputed = false; casa::Int = int; casa::Bool = bool]':
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2.cc:2987:1:   required from here
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:417:13: error: 'class casa::Cube<bool>' has no member named 'reformOrResize'
             this->getItem().reformOrResize (shape, False);
             ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:447:17: error: 'class casa::Cube<bool>' has no member named 'adjustLastAxis'
                 this->getItem().adjustLastAxis (desiredShape, 20);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:454:17: error: 'class casa::Cube<bool>' has no member named 'reformOrResize'
                 this->getItem().reformOrResize (desiredShape);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h: In instantiation of 'void casa::vi::VbCacheItemArray<T, IsComputed>::appendRows(casa::Int, casa::Bool) [with T = casa::Array<bool>; bool IsComputed = false; casa::Int = int; casa::Bool = bool]':
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2.cc:2987:1:   required from here
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:417:13: error: 'class casa::Array<bool>' has no member named 'reformOrResize'
             this->getItem().reformOrResize (shape, False);
             ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:447:17: error: 'class casa::Array<bool>' has no member named 'adjustLastAxis'
                 this->getItem().adjustLastAxis (desiredShape, 20);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:454:17: error: 'class casa::Array<bool>' has no member named 'reformOrResize'
                 this->getItem().reformOrResize (desiredShape);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h: In instantiation of 'void casa::vi::VbCacheItemArray<T, IsComputed>::appendRows(casa::Int, casa::Bool) [with T = casa::Vector<float>; bool IsComputed = false; casa::Int = int; casa::Bool = bool]':
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2.cc:2987:1:   required from here
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:417:13: error: 'class casa::Vector<float>' has no member named 'reformOrResize'
             this->getItem().reformOrResize (shape, False);
             ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:447:17: error: 'class casa::Vector<float>' has no member named 'adjustLastAxis'
                 this->getItem().adjustLastAxis (desiredShape, 20);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:454:17: error: 'class casa::Vector<float>' has no member named 'reformOrResize'
                 this->getItem().reformOrResize (desiredShape);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h: In instantiation of 'void casa::vi::VbCacheItemArray<T, IsComputed>::appendRows(casa::Int, casa::Bool) [with T = casa::Vector<double>; bool IsComputed = false; casa::Int = int; casa::Bool = bool]':
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2.cc:2987:1:   required from here
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:417:13: error: 'class casa::Vector<double>' has no member named 'reformOrResize'
             this->getItem().reformOrResize (shape, False);
             ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:447:17: error: 'class casa::Vector<double>' has no member named 'adjustLastAxis'
                 this->getItem().adjustLastAxis (desiredShape, 20);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:454:17: error: 'class casa::Vector<double>' has no member named 'reformOrResize'
                 this->getItem().reformOrResize (desiredShape);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h: In instantiation of 'void casa::vi::VbCacheItemArray<T, IsComputed>::appendRows(casa::Int, casa::Bool) [with T = casa::Vector<casa::MDirection>; bool IsComputed = false; casa::Int = int; casa::Bool = bool]':
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2.cc:2987:1:   required from here
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:417:13: error: 'class casa::Vector<casa::MDirection>' has no member named 'reformOrResize'
             this->getItem().reformOrResize (shape, False);
             ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:447:17: error: 'class casa::Vector<casa::MDirection>' has no member named 'adjustLastAxis'
                 this->getItem().adjustLastAxis (desiredShape, 20);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:454:17: error: 'class casa::Vector<casa::MDirection>' has no member named 'reformOrResize'
                 this->getItem().reformOrResize (desiredShape);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h: In instantiation of 'void casa::vi::VbCacheItemArray<T, IsComputed>::appendRows(casa::Int, casa::Bool) [with T = casa::Cube<std::complex<float> >; bool IsComputed = false; casa::Int = int; casa::Bool = bool]':
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2.cc:2987:1:   required from here
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:417:13: error: 'class casa::Cube<std::complex<float> >' has no member named 'reformOrResize'
             this->getItem().reformOrResize (shape, False);
             ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:447:17: error: 'class casa::Cube<std::complex<float> >' has no member named 'adjustLastAxis'
                 this->getItem().adjustLastAxis (desiredShape, 20);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:454:17: error: 'class casa::Cube<std::complex<float> >' has no member named 'reformOrResize'
                 this->getItem().reformOrResize (desiredShape);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h: In instantiation of 'void casa::vi::VbCacheItemArray<T, IsComputed>::appendRows(casa::Int, casa::Bool) [with T = casa::Vector<casa::SquareMatrix<std::complex<float>, 2> >; bool IsComputed = true; casa::Int = int; casa::Bool = bool]':
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2.cc:2987:1:   required from here
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:417:13: error: 'class casa::Vector<casa::SquareMatrix<std::complex<float>, 2> >' has no member named 'reformOrResize'
             this->getItem().reformOrResize (shape, False);
             ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:447:17: error: 'class casa::Vector<casa::SquareMatrix<std::complex<float>, 2> >' has no member named 'adjustLastAxis'
                 this->getItem().adjustLastAxis (desiredShape, 20);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:454:17: error: 'class casa::Vector<casa::SquareMatrix<std::complex<float>, 2> >' has no member named 'reformOrResize'
                 this->getItem().reformOrResize (desiredShape);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h: In instantiation of 'void casa::vi::VbCacheItemArray<T, IsComputed>::appendRows(casa::Int, casa::Bool) [with T = casa::Vector<int>; bool IsComputed = false; casa::Int = int; casa::Bool = bool]':
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2.cc:2987:1:   required from here
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:417:13: error: 'class casa::Vector<int>' has no member named 'reformOrResize'
             this->getItem().reformOrResize (shape, False);
             ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:447:17: error: 'class casa::Vector<int>' has no member named 'adjustLastAxis'
                 this->getItem().adjustLastAxis (desiredShape, 20);
                 ^
/build/casasynthesis-0.1/msvis/MSVis/VisBufferImpl2Internal.h:454:17: error: 'class casa::Vector<int>' has no member named 'reformOrResize'
                 this->getItem().reformOrResize (desiredShape);
                 ^
make[2]: *** [msvis/CMakeFiles/libmsvis.dir/MSVis/VisBufferImpl2.cc.o] Error 1
make[2]: Leaving directory `/build/casasynthesis-0.1/obj-x86_64-linux-gnu'
make[1]: *** [msvis/CMakeFiles/libmsvis.dir/all] Error 2
make[1]: Leaving directory `/build/casasynthesis-0.1/obj-x86_64-linux-gnu'
make: *** [all] Error 2
```

**Comment by gijzelaerr** [comment]
ah was using casacore 2.0.0, forcing build with 2.0.3 in the debian files now
