### ISSUE TITLE
doesn't compile with casacore 3.0

### ISSUE THREAD

**Issue by gijzelaerr** [radio-astro/casasynthesis#15]
```
/build/casasynthesis-0.1/obj-x86_64-linux-gnu/try_run.cc: In function 'int main()':                       
/build/casasynthesis-0.1/obj-x86_64-linux-gnu/try_run.cc:10:18: error: 'casa' has not been declared       
     std::cout << casa::getVersionCASA();                                                                 
                  ^~~~                                                                                    
CMakeFiles/cmTC_de1e1.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_de1e1.dir/try_run.cc.o' failed
make[1]: *** [CMakeFiles/cmTC_de1e1.dir/try_run.cc.o] Error 1                                             
make[1]: Leaving directory '/build/casasynthesis-0.1/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'            
Makefile:126: recipe for target 'cmTC_de1e1/fast' failed                                                  
make: *** [cmTC_de1e1/fast] Error 2                                                                       
```

**Comment by gervandiepen** [comment]
The namespace has changed to casacore.
There are scripts (in casacore/changescripts) to update the sources (also
for moved casacore header files), but it is the question if you want to put
all synthesis code in the casacore namespace. If not, more manual work is
needed to use the correct namespace.
Note that CASA uses the casa namespace for their synthesis code.

**Comment by gijzelaerr** [comment]
i did some find/replace going from `casa::` to `casacore::` but then other things break. personally I don't care that much but I think @o-smirnov has software depending on this prehistoric sheit.
